{% set version = '6.0-79' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-caret
  version: {{ version|replace("-", "_") }}

source:
  fn: caret_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/caret_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/caret/caret_{{ version }}.tar.gz
  sha256: 146a998fd300b54ac5a1cb827dfc5d4c520b7a4afb95bf0792d5bc740497dac4

build:
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-modelmetrics >=1.1.0
    - r-foreach
    - r-ggplot2
    - r-lattice >=0.20
    - r-nlme
    - r-plyr
    - r-recipes >=0.0.1
    - r-reshape2
    - r-withr >=2.0.0
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - r-modelmetrics >=1.1.0
    - r-foreach
    - r-ggplot2
    - r-lattice >=0.20
    - r-nlme
    - r-plyr
    - r-recipes >=0.0.1
    - r-reshape2
    - r-withr >=2.0.0
    - libgcc  # [not win]

test:
  commands:
    - $R -e "library('caret')"  # [not win]
    - "\"%R%\" -e \"library('caret')\""  # [win]

about:
  home: https://github.com/topepo/caret/
  license: GPL (>= 2)
  summary: Misc functions for training and plotting classification and regression models.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
