{% set version = '6.0-81' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-caret
  version: {{ version|replace("-", "_") }}

source:
  fn: caret_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/caret_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/caret/caret_{{ version }}.tar.gz
  sha256: ecbae3f5d11fa7d7b0e2525f5574616eeb61c4b82eaf8796014ee02fa7ce2bba

build:
  merge_build_host: True  # [win]
  number: 1000
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-lattice >=0.20
    - r-ggplot2
    - r-foreach
    - r-plyr
    - r-modelmetrics >=1.1.0
    - r-nlme
    - r-reshape2
    - r-recipes >=0.1.4
    - r-withr >=2.0.0
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-lattice >=0.20
    - r-ggplot2
    - r-foreach
    - r-plyr
    - r-modelmetrics >=1.1.0
    - r-nlme
    - r-reshape2
    - r-recipes >=0.1.4
    - r-withr >=2.0.0

test:
  commands:
    - $R -e "library('caret')"           # [not win]
    - "\"%R%\" -e \"library('caret')\""  # [win]

about:
  home: https://github.com/topepo/caret/
  license: GPL (>= 2)
  summary: Misc functions for training and plotting classification and regression models.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
