{% set version = "6.0-90" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-caret
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/caret_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/caret/caret_{{ version }}.tar.gz
  sha256: e851a4ed7d939c665e57e3551a5464b09fe4285e7c951236efdd890b0da866bc

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-modelmetrics             # [build_platform != target_platform]
    - r-plyr                     # [build_platform != target_platform]
    - r-recipes                  # [build_platform != target_platform]
    - r-nlme                     # [build_platform != target_platform]
    - r-reshape2                 # [build_platform != target_platform]
    - r-foreach                  # [build_platform != target_platform]
    - r-proc                     # [build_platform != target_platform]
    - r-lattice                  # [build_platform != target_platform]
    - r-ggplot2                  # [build_platform != target_platform]
    - r-withr                    # [build_platform != target_platform]
    - r-e1071                    # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-modelmetrics >=1.2.2.2
    - r-e1071
    - r-foreach
    - r-ggplot2
    - r-lattice >=0.20
    - r-nlme
    - r-proc
    - r-plyr
    - r-recipes >=0.1.10
    - r-reshape2
    - r-withr >=2.0.0
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-modelmetrics >=1.2.2.2
    - r-e1071
    - r-foreach
    - r-ggplot2
    - r-lattice >=0.20
    - r-nlme
    - r-proc
    - r-plyr
    - r-recipes >=0.1.10
    - r-reshape2
    - r-withr >=2.0.0

test:
  commands:
    - $R -e "library('caret')"           # [not win]
    - "\"%R%\" -e \"library('caret')\""  # [win]

about:
  home: https://github.com/topepo/caret/
  license: GPL-2.0-or-later
  summary: Misc functions for training and plotting classification and regression models.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: caret
# Title: Classification and Regression Training
# Version: 6.0-89
# Authors@R: c(person(given = "Max", family = "Kuhn", role = c("aut", "cre"), email = "mxkuhn@gmail.com"), person(given = "Jed", family = "Wing", role = "ctb"), person(given = "Steve", family = "Weston", role = "ctb"), person(given = "Andre", family = "Williams", role = "ctb"), person(given = "Chris", family = "Keefer", role = "ctb"), person(given = "Allan", family = "Engelhardt", role = "ctb"), person(given = "Tony", family = "Cooper", role = "ctb"), person(given = "Zachary", family = "Mayer", role = "ctb"), person(given = "Brenton", family = "Kenkel", role = "ctb"), person(given = "R Core Team", role = "ctb"), person(given = "Michael", family = "Benesty", role = "ctb"), person(given = "Reynald", family = "Lescarbeau", role = "ctb"), person(given = "Andrew", family = "Ziem", role = "ctb"), person(given = "Luca", family = "Scrucca", role = "ctb"), person(given = "Yuan", family = "Tang", role = "ctb"), person(given = "Can", family = "Candan", role = "ctb"), person(given = "Tyler", family = "Hunt", role = "ctb"))
# Description: Misc functions for training and plotting classification and regression models.
# License: GPL (>= 2)
# URL: https://github.com/topepo/caret/
# BugReports: https://github.com/topepo/caret/issues
# Depends: ggplot2, lattice (>= 0.20), R (>= 3.2.0)
# Imports: e1071, foreach, grDevices, methods, ModelMetrics (>= 1.2.2.2), nlme, plyr, pROC, recipes (>= 0.1.10), reshape2, stats, stats4, utils, withr (>= 2.0.0)
# Suggests: BradleyTerry2, covr, Cubist, dplyr, earth (>= 2.2-3), ellipse, fastICA, gam (>= 1.15), ipred, kernlab, klaR, knitr, MASS, Matrix, mda, mgcv, mlbench, MLmetrics, nnet, pamr, party (>= 0.9-99992), pls, proxy, randomForest, RANN, rmarkdown, rpart, spls, subselect, superpc, testthat (>= 0.9.1), themis (>= 0.1.3)
# VignetteBuilder: knitr
# Encoding: UTF-8
# RoxygenNote: 7.1.2
# NeedsCompilation: yes
# Packaged: 2021-09-27 17:39:41 UTC; max
# Author: Max Kuhn [aut, cre], Jed Wing [ctb], Steve Weston [ctb], Andre Williams [ctb], Chris Keefer [ctb], Allan Engelhardt [ctb], Tony Cooper [ctb], Zachary Mayer [ctb], Brenton Kenkel [ctb], R Core Team [ctb], Michael Benesty [ctb], Reynald Lescarbeau [ctb], Andrew Ziem [ctb], Luca Scrucca [ctb], Yuan Tang [ctb], Can Candan [ctb], Tyler Hunt [ctb]
# Maintainer: Max Kuhn <mxkuhn@gmail.com>
# Repository: CRAN
# Date/Publication: 2021-09-28 14:00:13 UTC
