appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: qFOTjZ+4ROTfQTVNX4TQKgwiIgJANd4L43IsygCLzXpK0XslXZHENd+WRCI0TT0dzUKjvpTGIQj93IQwx+uyj6uXjEikQTTnPgmkaOvcRxOvja2qcJ9HjWXAo7c52qUZCL49dVigWM+ZJ9YKwGTUXza80iajnBLMJmrvgnF4BeYh2b6LTyhiciNKvjKks3rr6uIFpOz4UyRE2Wt6ES/RSwTqMXU3CyETXE+S+tLTjrUVqtDsJYTJp4Ef6LXZ6Q75j2S0hpC7o6ZmP0ZTFqMeEBUlGdCNhvLpRPfSnLvns7v9m35TWIBEc9XI6en7Bzxl5N4zZTMkey9GLd2omDc5OqYrPodolueL2yZAb9ZAJz76FgZ9uRN8pi7PRJKNzfZbk+zTqgwU1kF4YVzilaPDBfjqV/PovFqKOUJ3XxTRf0hPmhMcS3+kUvJEWH1AYDu+BdMZPCEAWYei0b0b+Ee9aVw87C4P6bymhk0gt7Bq4KRaWGP3jc57LA9pttLUQ26ZAfb9uWZe6FJ4D4IHRqDKPDteROdQ/ZWOBR6hg1f/zzY/OvbxlE+worf9c5vgPGCJgaojRdwKTXa4dUUaJMuDkJmJIXmilFCAamnhpp/pU5oimifoj8fi7VgyqEB6HoXNn5PK3gMYmkXFaBwcR/rDuaAZIHHsV5L4PX0NHzAOV1E=}
bot:
  automerge: true
